instrumentation:
  root: 'src'
  excludes:
    - 'container.js'
    - 'app/Application.js'
    - 'interfaces/http/Server.js'
    - 'interfaces/http/router.js'
    - 'interfaces/http/logging/*.js'
    - 'interfaces/http/utils/*.js'
reporting:
  reports:
    - html
    - lcov
